version: '2.1'

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data:/backup
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    command: mongod --smallfiles --logpath /dev/null
    restart: 'no'
